# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /csehome/sdu6342/hsd/lab5_0406/lab5_0406.cache/wt [current_project]
set_property parent.project_path /csehome/sdu6342/hsd/lab5_0406/lab5_0406.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /csehome/sdu6342/hsd/lab5_0406/lab5_0406.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /csehome/sdu6342/hsd/lab5_0406/lab5_0406.srcs/sources_1/new/counter.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /csehome/sdu6342/hsd/lab5_0406/lab5_0406.srcs/constrs_1/new/sw2led.xdc
set_property used_in_implementation false [get_files /csehome/sdu6342/hsd/lab5_0406/lab5_0406.srcs/constrs_1/new/sw2led.xdc]

read_xdc /csehome/sdu6342/hsd/lab5_0406/lab5_0406.srcs/constrs_1/new/counter.xdc
set_property used_in_implementation false [get_files /csehome/sdu6342/hsd/lab5_0406/lab5_0406.srcs/constrs_1/new/counter.xdc]


synth_design -top counter -part xc7z020clg484-1


write_checkpoint -force -noxdef counter.dcp

catch { report_utilization -file counter_utilization_synth.rpt -pb counter_utilization_synth.pb }
